-- Add Meta Conversions API config to organizations
ALTER TABLE organizations ADD COLUMN IF NOT EXISTS meta_pixel_id TEXT DEFAULT NULL;
ALTER TABLE organizations ADD COLUMN IF NOT EXISTS meta_conversions_token TEXT DEFAULT NULL;

-- Add UTM tracking fields to contacts
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS utm_source TEXT DEFAULT NULL;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS utm_medium TEXT DEFAULT NULL;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS utm_campaign TEXT DEFAULT NULL;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS utm_content TEXT DEFAULT NULL;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS utm_term TEXT DEFAULT NULL;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS fbclid TEXT DEFAULT NULL;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS fbc TEXT DEFAULT NULL;

-- Add UTM tracking fields to bookings
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS utm_source TEXT DEFAULT NULL;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS utm_medium TEXT DEFAULT NULL;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS utm_campaign TEXT DEFAULT NULL;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS utm_content TEXT DEFAULT NULL;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS utm_term TEXT DEFAULT NULL;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS fbclid TEXT DEFAULT NULL;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS fbc TEXT DEFAULT NULL;
